GET http://laravel-1.test/api/users

###

GET http://laravel-1.test/api/users/1

###

POST http://laravel-1.test/api/users/create
content-type: application/json

{
  "first_name": "apiTest12",
  "last_name": "random2",
  "email": "random12@one.com"
}

###

GET http://laravel-1.test/users

###

GET http://laravel-1.test/api/users/16


// cURL command to test creating a new user.
curl -X POST -H "Content-Type: application/json" -d '{"first_name": "Brendan", "last_name": "Eich", "email": "beich@javascript.com"}' http://laravel-1.test/api/users/create | json_pp

// cURL command to test updating a user.
curl -X POST -H "Content-Type: application/json" -d '{"first_name": "Ken", "last_name": "Thompson", "email": "kthompson@unix.com"}' http://laravel-1.test/api/users/create | json_pp

curl -X POST -H "Content-Type: application/json" -d '{"email": "beich@javascript.com"}' http://laravel-1.test/api/users/update/9 | json_pp
